### ISSUE TITLE
Lab3 Step3のビルドでAssertionError

### ISSUE THREAD

**Issue by nobusue** [team-ohc-jp-place/cloud-native-workshop-v2m4-guides#4]
https://github.com/team-ohc-jp-place/cloud-native-workshop-v2m4-guides/blob/ocp-4.9-jp/event-driven-services.adoc#3-cart-service-%E3%81%B8-kafka-%E3%82%AF%E3%83%A9%E3%82%A4%E3%82%A2%E3%83%B3%E3%83%88%E3%82%92%E8%BF%BD%E5%8A%A0%E3%81%99%E3%82%8B

```
mvn clean package -DskipTests -DskipTests -f $CHE_PROJECTS_ROOT/cloud-native-workshop-v2m4-labs/cart-service && \
oc label dc/cart app.kubernetes.io/part-of=cart --overwrite &&  \
oc annotate dc/cart app.openshift.io/connects-to=my-cluster,datagrid-service --overwrite
```

こちらの実行時にAssertionErrorが発生してビルドが失敗する。

```
Exception in thread "main" java.lang.AssertionError
        at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
        at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
 
```

**Comment by nobusue** [comment]
CartResource.javaにimport文が足りないのが原因か?

`import javax.ws.rs.core.MediaType;` を追加したらビルドが通るようになった。
この対応で良いか、以降の手順を確認する。
